Bookstore.Web/Areas/Admin/Controllers/BookController.cs
using System;
using System.Linq;
using System.Linq.Expressions;
using Bookstore.Core.Entities;
using Bookstore.Core.Repositories;
using Bookstore.Web.Areas.Admin.Models;
using Bookstore.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class BookController : Controller
    {
        private readonly IUnitOfWork _uow;

        public BookController(IUnitOfWork uow) => _uow = uow;

        [Route("[area]/books")]
        public IActionResult List(BookListViewModel model)
        {
            model.Publishers = _uow.PublisherRepository.All();

            Expression<Func<Book, bool>> filter = null;
            if (Guid.TryParse(model.CurrentPublisher, out var currentPublisher))
                filter = x => x.PublisherId == currentPublisher;
            else if (model.CurrentPublisher == "None")
                filter = x => x.PublisherId == null;

            model.Books = _uow.BookRepository.All(filter);
            return View(model);
        }

        [HttpGet("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult Edit(Guid id)
        {
            var book = _uow.BookRepository.Get(id);
            if (book == null)
                return NotFound();
            
            var model = new BookEditModel
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                PublicationDate = book.PublicationDate,
                PublisherId = book.Publisher?.Id.ToString() ?? "None",
                Rating = book.Rating,
                CoverImage = book.CoverImage
            };

            model.Publishers = _uow.PublisherRepository.All();

            return View(model);
        }

        [HttpPost("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult Edit(BookEditModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var book = _uow.BookRepository.Get(model.Id);
            if (book == null)
                return NotFound();

            book.Title = model.Title;
            book.Description = model.Description;
            book.Publisher = Guid.TryParse(model.PublisherId, out var publisher) ? _uow.PublisherRepository.Get(publisher) : null;
            book.PublicationDate = model.PublicationDate;
            book.Rating = model.Rating;
            book.CoverImage = model.CoverImage;
            
            _uow.Commit();

            return RedirectToAction("List");
        }

        [Route("[area]/[controller]/[action]")]
        public IActionResult Create(BookEditModel model)
        {
            if (model == null || !ModelState.IsValid)
            {
                model = new BookEditModel();
                model.Publishers = _uow.PublisherRepository.All();
                return View(model);
            }

            var book = new Book
            {
                Title = model.Title,
                Description = model.Description,
                CoverImage = model.CoverImage,
                PublicationDate = model.PublicationDate,
                Rating = model.Rating,
                Publisher = Guid.TryParse(model.PublisherId, out var publisher) ? _uow.PublisherRepository.Get(publisher) : null
            };
            
            _uow.BookRepository.Insert(book);
            _uow.Commit();
            
            return RedirectToAction("List");
        }

        [Route("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult EditAuthors(Guid id)
        {
            var book = _uow.BookRepository.Get(id);
            if (book == null)
                return NotFound();
            
            var model = new AuthorsEditModel
            {
                BookId = id,
                CurrentAuthors = book.BookAuthors.Select(x => x.Author)
            };
            model.OtherAuthors = _uow.AuthorRepository.All().Except(model.CurrentAuthors);
            
            return View(model);
        }

        [HttpPost("[area]/[controller]/[action]")]
        public IActionResult AddAuthor(AuthorsEditModel model)
        {
            if (!ModelState.IsValid)
                return View("EditAuthors", model);

            var book = _uow.BookRepository.Get(model.BookId);
            var author = _uow.AuthorRepository.Get(model.AuthorId);
            
            if (author != null && book != null)
            {
                book.BookAuthors.Add(new BookAuthor
                {
                    BookId = book.Id,
                    Book = book,
                    AuthorId = author.Id,
                    Author = author
                });
                _uow.BookRepository.Update(book);
                _uow.Commit();
            }

            return RedirectToAction("EditAuthors", new {id = model.BookId});
        }
        
        [HttpPost("[area]/[controller]/[action]")]
        public IActionResult DeleteAuthor(AuthorsEditModel model)
        {
            if (!ModelState.IsValid)
                return View("EditAuthors", model);
            
            var book = _uow.BookRepository.Get(model.BookId);
            var author = _uow.AuthorRepository.Get(model.AuthorId);
            
            if (author != null && book != null)
            {
                var ba = book.BookAuthors.SingleOrDefault(x => x.BookId == book.Id && x.AuthorId == author.Id);
                book.BookAuthors.Remove(ba);
                _uow.BookRepository.Update(book);
                _uow.Commit();
            }

            return RedirectToAction("EditAuthors", new {id = model.BookId});
        }

        [Route("[area]/[controller]/[action]/{id:guid}")]
        public IActionResult Delete(Guid id)
        {
            _uow.BookRepository.Delete(id);
            _uow.Commit();
            
            return RedirectToAction("List");
        }
    }
}

Bookstore.Web/Areas/Api/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Bookstore.Core.Entities;
using Bookstore.Core.Repositories;
using Bookstore.Web.Areas.Api.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Web.Areas.Api.Controllers
{
    [Area("Api")]
    [ApiController]
    public class BookController : ControllerBase
    {
        private readonly IUnitOfWork _uow;

        public BookController(IUnitOfWork uow) => _uow = uow;
        
        [HttpGet("[area]/books")]
        public IEnumerable<BookModel> List()
        {
            return _uow.BookRepository.All().Select(Map);
        }

        [HttpGet("[area]/books/{id:guid}")]
        public ActionResult<BookModel> Get(Guid id)
        {
            var book = _uow.BookRepository.Get(id);
            if (book == null)
                return NotFound();

            return Ok(Map(book));
        }
    
        // Map Book object to serializable BookModel
        private BookModel Map(Book book)
        {
            return new BookModel
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                CoverImage = book.CoverImage,
                Rating = book.Rating,
                PublicationDate = book.PublicationDate,
                Publisher = book.Publisher?.Name,
                Authors = book.BookAuthors.Select(x => x.Author.ToString())
            };
        }
    }
}

Bookstore.Web/Controllers/AuthorController.cs
using System;
using Bookstore.Core.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Web.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IUnitOfWork _uow;
    
        public AuthorController(IUnitOfWork uow) => _uow = uow;

        [Route("authors")]
        public IActionResult List()
        {
            return View(_uow.AuthorRepository.All());
        }

        [Route("[controller]/[action]/{id:guid}")]
        public IActionResult Details(Guid id)
        {
            var author = _uow.AuthorRepository.Get(id);
            return author == null ? (IActionResult) NotFound() : View(author);
        }
    }
}

Bookstore.Web/Controllers/BookController.cs
using System;
using System.Linq.Expressions;
using Bookstore.Core.Entities;
using Bookstore.Core.Repositories;
using Bookstore.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Web.Controllers
{
    public class BookController : Controller
    {
        private readonly IUnitOfWork _uow;

        public BookController(IUnitOfWork uow) => _uow = uow;

        [Route("")]
        public IActionResult List(BookListViewModel model)
        {
            model.Publishers = _uow.PublisherRepository.All();

            Expression<Func<Book, bool>> filter = null;
            if (Guid.TryParse(model.CurrentPublisher, out var currentPublisher))
                filter = x => x.PublisherId == currentPublisher;
            else if (model.CurrentPublisher == "None")
                filter = x => x.PublisherId == null;

            model.Books = _uow.BookRepository.All(filter);
            return View(model);
        }

        [Route("[controller]/[action]/{id:guid}")]
        public IActionResult Details(Guid id)
        {
            var book = _uow.BookRepository.Get(id);
            return book == null ? (IActionResult) NotFound() : View(book);
        }
    }
}

Bookstore.Web/Areas/Admin/Views/Book/Create.cshtml
@model BookEditModel

@{
    ViewBag.Title = "Add new book";
    
    var publishersList = new List<SelectListItem>(
        Model.Publishers.Select(x => new SelectListItem(x.Name, x.Id.ToString()))
    );
    publishersList.Add(new SelectListItem("None", "None"));
}

<div class="card">
    <div class="card-header">
        <h3>Add new book</h3>
    </div>
    <form asp-action="Edit" class="card-body">
        <input asp-for="Id"/>
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control-plaintext"/>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PublicationDate"></label>
            <input asp-for="PublicationDate" class="form-control"/>
            <span asp-validation-for="PublicationDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PublisherId"></label>
            <select asp-for="PublisherId" asp-items="publishersList" class="form-control"></select>
            <span asp-validation-for="PublisherId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Rating"></label>
            <input asp-for="Rating" class="form-control"/>
            <span asp-validation-for="Rating" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CoverImage"></label>
            <input asp-for="CoverImage" class="form-control"/>
            <span asp-validation-for="CoverImage" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-primary" value="Add"/>
    </form>
    <div class="card-footer text-right">
        <a asp-action="List" class="btn btn-outline-primary">Home</a>
    </div>
</div>

@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

Bookstore.Web/Areas/Admin/Views/Book/Edit.cshtml
@model BookEditModel

@{
    ViewBag.Title = "Edit book";
    
    var publishersList = new List<SelectListItem>(
        Model.Publishers.Select(x => new SelectListItem(x.Name, x.Id.ToString()))
    );
    publishersList.Add(new SelectListItem("None", "None"));
}

<div class="card">
    <div class="card-header">
        <h3>Edit book</h3>
    </div>
    <form asp-action="Edit" class="card-body">
        <input asp-for="Id"/>
        <div class="form-group">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control"/>
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" class="form-control"/>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PublicationDate"></label>
            <input asp-for="PublicationDate" class="form-control"/>
            <span asp-validation-for="PublicationDate" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PublisherId"></label>
            <select asp-for="PublisherId" asp-items="publishersList" class="form-control"></select>
            <span asp-validation-for="PublisherId" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Rating"></label>
            <input asp-for="Rating" class="form-control"/>
            <span asp-validation-for="Rating" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="CoverImage"></label>
            <input asp-for="CoverImage" class="form-control"/>
            <span asp-validation-for="CoverImage" class="text-danger"></span>
        </div>
        <input type="submit" class="btn btn-primary" value="Save"/>
    </form>
    <div class="card-footer text-right">
        <a asp-action="List" class="btn btn-outline-primary">Home</a>
    </div>
</div>

@section Scripts
{
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
}

Bookstore.Web/Areas/Admin/Views/Book/EditAuthors.cshtml
@model AuthorsEditModel

@{
    ViewBag.Title = "Edit authors"; 
    var otherAuthors = new List<SelectListItem>(Model.OtherAuthors.Select(x => new SelectListItem(x.ToString(), x.Id.ToString())));
}

<div class="card">
    <div class="card-header">
        <h3>Edit authors</h3>
    </div>
    <div class="card-body">
        @foreach (var author in Model.CurrentAuthors)
        {    
            <form asp-action="DeleteAuthor" class="mb-2">
                <input asp-for="BookId"/>
                <div class="d-flex flex-row w-25 justify-content-between">
                    <label>@author</label>
                    <input asp-for="AuthorId" value="@author.Id"/>
                    <input type="submit" class="btn btn-outline-danger" value="Delete"/>
                </div>
            </form>
        }
        @if (otherAuthors.Count > 0)
        {
            <form asp-action="AddAuthor">
                <input asp-for="BookId"/>
                <div class="d-flex flex-row w-25 justify-content-between">
                    <select asp-for="AuthorId" asp-items="otherAuthors"></select>
                    <input type="submit" class="btn btn-primary" value="Add"/>
                </div>
            </form>
        }
    </div>
    <div class="card-footer text-right">
        <a asp-action="List" class="btn btn-outline-primary">Home</a>
    </div>
</div>

Bookstore.Web/Areas/Admin/Views/Book/List.cshtml
@using System.Text
@model Bookstore.Web.ViewModels.BookListViewModel

@{
    ViewBag.Title = "Books List";

    var list = new List<SelectListItem> {new SelectListItem("All", "All")};
    list.AddRange(Model.Publishers.Select(x => new SelectListItem(x.Name, x.Id.ToString())));
    list.Add(new SelectListItem("None", "None"));
}

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center w-100">
        <ul class="nav nav-pills card-header-pills">
            <li class="nav-item">
                <a class="nav-link" asp-area="" asp-controller="Book" asp-action="List">Books</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Author" asp-action="List">Authors</a>
            </li>
            <li class="nav-item nav-link active">
                Admin panel
            </li>
        </ul>
        <div class="d-flex flex-row">
            <form method="post" class="form-inline">
                <select asp-for="@Model.CurrentPublisher" asp-items="list" class="form-control mr-2"></select>
                <input type="submit" class="btn btn-primary mr-2" value="Filter"/>
            </form>
            <a class="btn btn-primary" asp-action="Create">Add new book</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-striped table-sm table-bordered">
            <tr>
                <th>Title</th>
                <th>Authors</th>
                <th>Publisher</th>
                <th>Publication Date</th>
                <th>Rating</th>
                <th class="text-center">Actions</th>
            </tr>
            @foreach (var book in Model.Books)
            {
                <tr>
                    <td>@book.Title</td>
                    <td>
                        @{
                            if (book.BookAuthors.Count == 0)
                            {
                                <i class="text-black-50">No info</i>
                            }
                            else
                            {
                                var names = new StringBuilder();
                                foreach (var ba in book.BookAuthors)
                                {
                                    names.Append($"{ba.Author}, ");
                                }
                                <text>@names.Remove(names.Length - 2, 2)</text>
                            }
                        }
                    </td>
                    <td>
                        @if (book.Publisher is null)
                        {
                            <i class="text-black-50">No info</i>
                        }
                        else
                        {
                            <text>@book.Publisher</text>
                        }
                    </td>
                    <td>
                        @if (book.PublicationDate.HasValue)
                        {
                            <text>@book.PublicationDate.Value.ToShortDateString()</text>
                        }
                        else
                        {
                            <i class="text-black-50">No info</i>
                        }
                    </td>
                    <td>
                        @if (book.Rating.HasValue)
                        {
                            <text>@book.Rating.ToString()</text>
                        }
                        else
                        {
                            <i class="text-black-50">No info</i>
                        }
                    </td>
                    <td class="text-center d-flex flex-row">
                        <a asp-action="Edit" asp-route-id="@book.Id" class="btn btn-outline-primary mr-2">Edit</a>
                        <a asp-action="EditAuthors" asp-route-id="@book.Id" class="btn btn-outline-primary mr-2">Authors</a>
                        <a asp-action="Delete" asp-route-id="@book.Id" class="btn btn-secondary">Delete</a>
                    </td>
                </tr>
            }
        </table>
    </div>
</div>